/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore-all lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        Kbd: typeof import('./src/components/kbd.vue')['default'];
        Mdi: typeof import('./src/components/mdi.vue')['default'];
        NA: typeof import('naive-ui')['NA'];
        NAvatar: typeof import('naive-ui')['NAvatar'];
        NButton: typeof import('naive-ui')['NButton'];
        NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
        NDivider: typeof import('naive-ui')['NDivider'];
        NEl: typeof import('naive-ui')['NEl'];
        NFlex: typeof import('naive-ui')['NFlex'];
        NForm: typeof import('naive-ui')['NForm'];
        NFormItem: typeof import('naive-ui')['NFormItem'];
        NH2: typeof import('naive-ui')['NH2'];
        NImage: typeof import('naive-ui')['NImage'];
        NInput: typeof import('naive-ui')['NInput'];
        NInputNumber: typeof import('naive-ui')['NInputNumber'];
        NLayout: typeof import('naive-ui')['NLayout'];
        NLayoutContent: typeof import('naive-ui')['NLayoutContent'];
        NLayoutSider: typeof import('naive-ui')['NLayoutSider'];
        NList: typeof import('naive-ui')['NList'];
        NListItem: typeof import('naive-ui')['NListItem'];
        NMenu: typeof import('naive-ui')['NMenu'];
        NP: typeof import('naive-ui')['NP'];
        NPopover: typeof import('naive-ui')['NPopover'];
        NResult: typeof import('naive-ui')['NResult'];
        NScrollbar: typeof import('naive-ui')['NScrollbar'];
        NSelect: typeof import('naive-ui')['NSelect'];
        NSpace: typeof import('naive-ui')['NSpace'];
        NSpin: typeof import('naive-ui')['NSpin'];
        NSplit: typeof import('naive-ui')['NSplit'];
        NTabPane: typeof import('naive-ui')['NTabPane'];
        NTabs: typeof import('naive-ui')['NTabs'];
        NTag: typeof import('naive-ui')['NTag'];
        NText: typeof import('naive-ui')['NText'];
        NTooltip: typeof import('naive-ui')['NTooltip'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
    }
}
